project:
  type: website

website:
  title: "fkwq-usgs-river-gauges"
  navbar:
    left:
      - href: index.qmd
        text: Home
        
      - href: okeeOutflow.qmd
        text: Okeechobee Outflows
        
      - text: Single Station View
        href: stationInspect.qmd

      - text: Downstream Flows
        menu:
        - riverflows/riverflowSouth.qmd
        - riverflows/riverflowEast.qmd
        - riverflows/riverflowWest.qmd
        - riverflows/riverflowSoutheast.qmd
        - riverflows/riverflowSouthwest.qmd
        
      - text: Regional Outflows
        menu:
        - outflows/outflowNorth.qmd
        - outflows/outflowWest.qmd
        - outflows/outflowSouth.qmd
        - outflows/outflowEash.qmd
        - outflows/outflowCentral.qmd
        
      - href: https://github.com/marinebon/data_reports
        text: Source Code on GitHub
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    code-fold: true


